### ISSUE TITLE
Error when passing in unrecognizable emojis

### ISSUE THREAD

**Issue by aliashafi** [aaronpk/emoji-detector-php#15]
`\Emoji\detect_emoji($string)` seems to return an error if there are some number of unrecognizable emojis (or so thats my assumption). 

![Screen Shot 2021-09-02 at 5 00 13 PM](https://user-images.githubusercontent.com/20862546/131930723-b60f223b-5edf-496a-ac67-1f0a523b5e37.png)

Unfortunately, i do not know what emojis are causing this, but from our logs we can see here which strings are failing if that gives you any clues. 
<img width="478" alt="Screen Shot 2021-09-02 at 5 02 48 PM" src="https://user-images.githubusercontent.com/20862546/131930879-67b2ec70-1bf4-40b8-91a7-8c6c689016b6.png">

**Comment by aaronpk** [comment]
which PHP version are you using?

**Comment by aliashafi** [comment]
PHP 7.4.23

**Comment by loop01** [comment]
The problem is in Emoji.php on line 28. Change $mbOffset = mb_strpos($string, $ch, $lastMbOffset); with $mbOffset = strpos($string, $ch, $lastMbOffset); I solved it this way

**Comment by thedotedge** [comment]
Reproducible on 7.4.27.

**Comment by DavidGoodwin** [comment]
I'm experiencing this problem too - after upgrading from 0.2.1 to 0.3.1.

Triggered by e.g. 
```
"Not Wordle, just us improving your contact center experience. \n\n⬛️⬛️⬛️⬛️⬛ ️\n⬛️⬛️⬛️⬛️⬛ ️\n☎️🙅🏻‍♀️🙅🏾‍♂️⬛️⬛️\n⬛️⬛️⬛️📲🎉\n⬛️⬛️⬛️⬛️⬛️\n⬛️⬛️⬛️⬛️⬛ ️"
```

I'll guess it's due to : https://github.com/aaronpk/emoji-detector-php/commit/4e9af4bb040481b5c1f70c350415aa9957e9af2f
