### ISSUE TITLE
Non-qualified skin variations are not recognized

### ISSUE THREAD

**Issue by jonathanrhodes** [aaronpk/emoji-detector-php#18]
I saw that support for non-qualified emojis was added recently, but it appears that non-qualified skin variations are still unrecognized.

For example, `1F937 1F3FD 200D 2642` is defined in https://unicode.org/Public/emoji/14.0/emoji-test.txt, but `1F937-1F3FD-200D-2642` is not in [map.json](https://github.com/aaronpk/emoji-detector-php/blob/main/src/map.json).

----

I tried replacing the following code in the generator, which did regenerate the map properly.

```
  if(isset($emoji['skin_variations'])) {
    foreach($emoji['skin_variations'] as $key=>$var) {
      $map[$var['unified']] = $short_name;
    }
  }
```
to
```
  if(isset($emoji['skin_variations'])) {
    foreach($emoji['skin_variations'] as $key=>$var) {
      $map[$var['unified']] = $short_name;

      if(isset($var['non_qualified'])) {
        $map[$var['non_qualified']] = $short_name;
      }
    }
  }
```

However, I started getting errors about the regex being too large.

**Comment by aaronpk** [comment]
Thanks. With the refactor to remove the regex in 1fd7d46d841c8b181963a91c2fd7890cfa46296c I was able to add this
