### ISSUE TITLE
Add a function to strip all emojis

### ISSUE THREAD

**Issue by joelstein** [aaronpk/emoji-detector-php#20]
I'm using this library to strip all emojis from a string.

Here's the code, if you want to create a function for it in this package.

```php
$emojis = \Emoji\detect_emoji($string);

foreach (array_reverse($emojis) as $emoji) {
  $length = strlen($emoji['emoji']);
  $start = substr($string, 0, $emoji['byte_offset']);
  $end = substr($string, $emoji['byte_offset'] + $length, strlen($string) - ($emoji['byte_offset'] + $length));
  $string = $start . $end;
}
```

**Comment by aksafan** [comment]
Hey @joelstein,

I think you will be more than welcome to create a PR with this changes and appropriate tests to cover them and @aaronpk will review and merge it if everything is fine.

**Comment by Pnoexz** [comment]
I was also looking for this functionality. Since I'm handling the emojis in a different way, they appear as duplicated when I show the original string to the user. Hopefully it gets implemented soon

**Comment by aaronpk** [comment]
Thanks, this has been included in the library.

**Comment by joelstein** [comment]
Thanks!
