### ISSUE TITLE
Some emojis are not detected properly

### ISSUE THREAD

**Issue by s-k-georgiev** [aaronpk/emoji-detector-php#21]
☝ - this is **not** recognised as emoji

© - but this on is recognised as emoji, is it mistaken with ©️
®  - but this on is recognised as emoji, is it mistaken with ®️
™ - but this on is recognised as emoji, is it mistaken with ™️

**Comment by aksafan** [comment]
Hey @s-k-georgiev 

> ☝ - this is not recognised as emoji 
This was fixed [here](https://github.com/aaronpk/emoji-detector-php/commit/488cc3fda96ddb320be646551de5993af1599442#diff-dd465effe2f3e734082d23d7f38dd63afab6c16c5d2f6f59e337c5a5672ccd0fR3729) and added as a part of latest [release](https://github.com/aaronpk/emoji-detector-php/releases/tag/1.0.0).
I've even written a test to check this:
<img width="590" alt="image" src="https://github.com/aaronpk/emoji-detector-php/assets/14964793/63f38b93-a3c5-4e48-a6ad-71364ef2b9c4">
<img width="500" alt="image" src="https://github.com/aaronpk/emoji-detector-php/assets/14964793/f388be2e-ed44-45da-8897-af36ce0bdf66">

> © - but this on is recognised as emoji, is it mistaken with ©️
> ® - but this on is recognised as emoji, is it mistaken with ®️
> ™ - but this on is recognised as emoji, is it mistaken with ™️
As for this three, I see 2 [lines](https://github.com/aaronpk/emoji-detector-php/blob/main/src/map.json#L26-L27) in `map.json`:
    ```
    "00A9": "copyright",
    "00A9-FE0F": "copyright",
    ```
And in code I see it being recognized as `A9-FE0F` for ©️ and `A9` for ©.
Looks similar except that 2 zero signs at the beginning.

I think @aaronpk might be more familiar with this situation.

**Comment by s-k-georgiev** [comment]
@aksafan Please take a look at the official list: 
https://unicode.org/Public/emoji/15.1/emoji-sequences.txt

You can search for `00A9`, and there is only 1 match because this is the emoji symbol:     
`"00A9-FE0F": "copyright"`

![Screenshot 2023-11-30 at 16 54 37](https://github.com/aaronpk/emoji-detector-php/assets/104416551/e5f6740a-83d7-4a3e-980d-d1e16232f53d)

The other one is ASCII symbol:
`"00A9": "copyright"`

**Comment by aksafan** [comment]
@s-k-georgiev thanks for сlarification!

**Comment by slaviboy** [comment]
@aksafan My bad, it seems `00A9` is also set as Emoji, but of type 'unqualified'
https://unicode.org/Public/emoji/15.1/emoji-test.txt
