### ISSUE TITLE
Fails to factor in gender

### ISSUE THREAD

**Issue by RandomDude777** [aaronpk/emoji-detector-php#4]
💂🏿‍♀️ should return:
1f482-1f3ff-200d-2640-fe0f (woman guard: dark skin tone)
https://abs.twimg.com/emoji/v2/72x72/1f482-1f3ff-200d-2640-fe0f.png

instead it returns 2 separate emojis:

guardsman: dark skin tone
female_sign

**Comment by aaronpk** [comment]
is this guardsman emoji new? I might need to update the list of emoji again.

**Comment by RandomDude777** [comment]
the formatting in the base json has changed.
in generate-map.php

fix:

change line from:
$map[$emoji['unified'] . '-' . $key] = $emoji['short_name'];

to:
 $map[$var['unified']] = $emoji['short_name'];

**Comment by aaronpk** [comment]
sidenote: apparently GitHub hasn't updated their emoji library yet either because I still see two symbols on your original comment :joy:

![screenshot 2017-11-30 12 28 06](https://user-images.githubusercontent.com/113001/33453298-ee7f7b38-d5c9-11e7-8871-d3a718e5bf87.png)

**Comment by RandomDude777** [comment]
You're doing better than me! I cant even see it lol https://i.imgur.com/5xcIREJ.png
