### ISSUE TITLE
PHP 5.3 Compatibility

### ISSUE THREAD

**Issue by dshanske** [aaronpk/emoji-detector-php#5]
We're using this now in Semantic Linkbacks. This library uses short array notation. Being as this is the only issue for PHP 5.3 compatibility, would you consent to not using short array notation in order to encourage compatibility as it is not a breaking change?

 7 | ERROR   | [ ] Short array syntax (open) is available since 5.4
 7 | ERROR   | [ ] Short array syntax (close) is available since 5.4
 19 | ERROR   | [ ] Short array syntax (open) is available since 5.4
 19 | ERROR   | [ ] Short array syntax (close) is available since 5.4
 32 | ERROR   | [ ] Short array syntax (open) is available since 5.4
 38 | ERROR   | [ ] Short array syntax (close) is available since 5.4
 44 | ERROR   | [ ] Short array syntax (open) is available since 5.4
 51 | ERROR   | [ ] Short array syntax (close) is available since 5.4

**Comment by aaronpk** [comment]
Sure, that sounds reasonable to me!

**Comment by dshanske** [comment]
Great.

**Comment by aaronpk** [comment]
This is done, and is now tested under PHP 5.3 on Travis.

https://travis-ci.org/aaronpk/emoji-detector-php

Released as [0.2.1](https://github.com/aaronpk/emoji-detector-php/releases/tag/0.2.1)
