### ISSUE TITLE
Not all emojis.

### ISSUE THREAD

**Issue by Sieboldianus** [aaronpk/emoji-detector-php#6]
Great library!

I have only one issue: some "older" emojis such as ❤ are not detected. I know this is a general problem of the definition "emoji", but what is the difference between ❤ and 🏰💍💑? I think none, they're all emojis to me. However:
- 🏰💍💑 are detected
- ❤ is not detected

**Comment by aaronpk** [comment]
I just added a test for the red heart emoji, and it does detect it. I suspect what you're referring to is the unicode heart character: ❤︎ ?

**Comment by Sieboldianus** [comment]
Strange, if I do this:
```
$string_text = 🏰💍💑❤;
$eMatches = Emoji\detect_emoji($string_text);
$emojis = implode(';', array_column($string_text, 'emoji')); //extract emojis
echo($emojis):
```
I'll get `🏰;💍;💑`. Maybe my ❤ is encoded differently? Apologies if this is rather an issue on my side! issue

**Comment by Teddytrombone** [comment]
I can confirm, that not all emojis are detected. If you test the official emoji data for v1.0 (http://unicode.org/Public/emoji/1.0/emoji-data.txt) then not all of them are recognized.

Here's a short example code, which reads the first 70 (relevant) lines of this file. The output only shows 20 of 70 emojis (e.g. ©, ☂ and ↔ are missing).

<pre>$content = file_get_contents('http://unicode.org/Public/emoji/1.0/emoji-data.txt');
$lines = explode("\n", $content);
$text = implode("\n", array_slice($lines, 34, 70));
$data = \Emoji\detect_emoji($text);
print_r($data);</pre>

It would be great, if you could fix this.

**Comment by msenol86** [comment]
Hi this emoji not detected too

http://unicode.org/emoji/charts/emoji-zwj-sequences.html#1f469_200d_2764_fe0f_200d_1f48b_200d_1f468

**Comment by daneren2005** [comment]
Looking at the raw data this is pulling emoji data from https://raw.githubusercontent.com/iamcal/emoji-data/master/emoji_pretty.json, it looks like we can make this work by adding 

```
if(isset($emoji['non_qualified'])) {
	$map[$emoji['non_qualified']] = $short_name;
}
```

to https://github.com/aaronpk/emoji-detector-php/blob/main/build/generate-map.php.  This adds the single byte emoji such as ❤ and ☂ which got changed to a 2-byte emoji in later standards.  Technically if you look at http://unicode.org/Public/emoji/1.0/emoji-data.txt they are listed as text, and in later standards where they have 2 bytes are listed as Emoji, so not detecting the single byte versions would be correct.  But realistically browsers show the single byte versions the exact same as the two byte versions.  You can't even tell that ❤ is different from ❤️ without selecting the text and doing `'❤️'.length` in a console.

I have a hard time reading these emoji standards.  Does anyone know if there are any times where trying to use this `non_qualified` field would detect something as an emoji when it really shouldn't?

**Comment by aaronpk** [comment]
Thanks for this! I'm going to ship this in the next update. I'm also curious if this will detect something as an emoji when it's not, but we'll wait for any reports about that to show up in the future, it's easy enough to take this out (or even make it optional) if needed.
